language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
addons:
  apt:
    packages:
      - kyototycoon
      - libkyototycoon-dev
install:
  - pip install cython msgpack-python
  - python setup.py build_ext -i
script:
  - python tests.py -v
